security:
    encoders:
        App\Entity\User:
            algorithm: argon2i

    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            pattern: ^/*
            anonymous: true
            guard:
                authenticators:
                    - App\Security\FacebookConnectAuthenticator
            provider: app_user_provider
            logout:
                path: logout


    access_control:
        - { path: ^/(|facebook)$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/*, role: IS_AUTHENTICATED_FULLY }