parameters:
    fb_graph_version: 'v3.2'

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/*'
        exclude: '../src/{DependencyInjection,Entity,Migrations,Tests,Kernel.php}'

    App\Controller\:
        resource: '../src/Controller'
        tags: ['controller.service_arguments']

    Facebook\Facebook:
        arguments:
            $config: {app_id: '%env(FB_ID)%', app_secret: '%env(FB_SECRET)%', default_graph_version: '%fb_graph_version%'}
